name: Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Debugging
        run: |
          # List the contents of the directory for debugging
          ls C:\actions-runner

          # Print the content of the .env file for debugging
          Get-Content 'C:\actions-runner\.env'

      - name: Set Content of .env file
        run: |
          # read the content of .env file in PowerShell and store it as a GitHub ENV variable
          $tests = Get-Content 'C:\actions-runner\.env' | Out-String
          echo "Tests=$tests" >> $GITHUB_ENV

      - name: Echo Content of .env file
        run: |
          # retrieve the GitHub ENV variable and echo the content
          echo "Content of .env file: ${{ env.Tests }}"
