name: build Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Select environment' 
    #     required: true
    #     type: environment
 
jobs:
  build:
    runs-on: windows-2019
    # continue-on-error: true
    steps:
    - name: build
      run: |
        # Add your deployment script or commands for the dev environment
          echo "build script"
      
  # Deploy-ab:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       target: [windows-2019]
        # runner: [windows-2019]
    # uses: ./.github/workflows/deployment2.yml
    # with:
    #   target-env: ${{ matrix.target }}
    #   # target-runner: ${{ matrix.runner }}
    # secrets: inherit

  # build:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]
  #       node: [14, 16]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node }}




  deploy-ab:
    needs: build
    runs-on: ${{ vars.RUNNER }}
    name: Deploy to ${{ vars.ENVIRONMENT }}
    strategy:
      matrix:
        environment: ${{ vars.ENVIRONMENT }}
    # if: needs.job1.outputs.approved == "${{ inputs.target-env }}"
    # continue-on-error: true
    environment:
      name: ${{matrix.environment}}
    steps:
      - run: echo "${{matrix.environment}}"
      - name: "Deploy to Prod"
        run: |
          # Add your deployment script or commands for the chosen environment
          echo "Deploying to ${{matrix.environment}} "

  # example_matrix:
  #   strategy:
  #     matrix:
  #       os: [windows-latest, ubuntu-latest]
  #       node: [14, 16]
  #   runs-on: ${{ matrix.os }}

  # Deploy:
  #   needs: build
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       environment: ${{ vars.ENVIRONMENT }}
  #       runner: ${{ vars.RUNNER }}

  #       # experimental: [false]
  #       # include:
  #         # - { environment: ${{ vars.ENVIRONMENT }}, runner-ap: ${{ vars.RUNNER }} }
  #         # - { environment: qa, runner-ap: windows-2019 } 
          
  #   uses: ./.github/workflows/deployment2.yml
  #   with:
  #     target-ap: ${{ matrix.runner }}
  #     target-env: ${{ matrix.environment }}
        
  # results:
  #   if: ${{ always() }}
  #   runs-on: ubuntu-latest
  #   name: Final Results
  #   needs: [Deploy]
  #   steps:
  #     - run: exit 1
  #       # see https://stackoverflow.com/a/67532120/4907315
  #       if: >-
  #         ${{
  #              contains(needs.*.result, 'failure')
  #           || contains(needs.*.result, 'cancelled')
  #           || contains(needs.*.result, 'skipped')
  #         }}


  # Deploy-ab:
  #   needs: build
  #   strategy:
  #     matrix:
  #       include:
  #         - { environment: dev, runner-ap: windows-2019, runner-dp: windows-latest }
  #         - { environment: qa, runner-ap: windows-2019, runner-dp: windows-latest } 
          
  #   uses: ./.github/workflows/deployment.yml
  #   with:
  #     target-ap: ${{ matrix.runner-ap }}
  #     target-dp: ${{ matrix.runner-dp }}
  #     target-env: ${{ matrix.environment }}
  # Deploy:
  #   needs: build
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       target: [windows-latest, ubuntu-latest]
  #       experimental: [true]
  #   uses: ./.github/workflows/deployment.yml
  #   with:
  #     target-exp: ${{ matrix.experimental }}
  #     target-env: ${{ matrix.target }}
  #   # secrets: inherit


# deploy-prod:
#     name: Deploy prod
#     needs: build
#     strategy:
#       matrix:
#         include:
#           - environment: windows-latest
#             # url: https://europe.my.service
#           - runner: windows-latest
#           - environment: ubuntu-latest
#             # url: https://europe.my.service
#           - runner: ubuntu-latest
#           # - env:
#           #     name: ${{vars.RUNNER}}
#     environment:
#       # url: ${{ matrix.url }}
#       name: ${{ matrix.environment }}
#     steps:
#     - name: deploy
#       uses: ./.github/workflows/deployment.yml
#       with:
#         # version: ${{ needs.deploy-staging.outputs.version }}
#         target-env: ${{ matrix.environment }}
#         target-runner: ${{ matrix.runner }}






  # Deploy-ab:
  #   needs: build
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       target: [windows-2019]
  #       # runner: [windows-2019]
  #   uses: ./.github/workflows/deployment2.yml
  #   with:
  #     target-env: ${{ matrix.target }}
  #     # target-runner: ${{ matrix.runner }}
  #   secrets: inherit
