name: Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Set Content of .env file
        run: |
          # read the content of .env file in PowerShell
          $envContent = Get-Content 'C:\actions-runner\.env'
          # loop through each line and echo the content
          foreach ($line in $envContent) {
            echo $line
          }

      - name: Echo environment variables
        run: |
          echo "FORMS-DB_PUBLISHPROFILE=$env:FORMS-DB_PUBLISHPROFILE"
          echo "FORMS-DB_DACPAC=$env:FORMS-DB_DACPAC"
          echo "FORMS-DB_CONNECTIONSTRING=$env:FORMS-DB_CONNECTIONSTRING"
