name: Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Set and Echo Content of .env file
        run: |
          # read the content of .env file in PowerShell and store it in a variable
          $tests = Get-Content 'C:\actions-runner\.env' | Out-String
  
          # set the content as a GitHub ENV variable
          echo "Tests=$tests" >> $GITHUB_ENV
  
          # echo the content of the .env file
          echo "Content of .env file: $tests"
