name: build Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Select environment'
    #     required: true
    #     type: environment

jobs:
  build:
    runs-on: windows-2019
    # continue-on-error: true
    steps:
    - name: build
      run: |
        # Add your deployment script or commands for the dev environment
          echo "build script"


  deploy:
    needs: build
    outputs:
      env_status: ${{ needs.build.outputs.env_status }}
    strategy:
      matrix:
        include:
          - { environment: dev, runner-ap: windows-2019 }
          - { environment: qa, runner-ap: windows-2019 } 
          
    runs-on: ${{ matrix.runner-ap }}
    
    steps:
      - name: Deploy
        uses: ./.github/workflows/deployment2.yml
        with:
          target-ap: ${{ matrix.runner-ap }}
          target-env: ${{ matrix.environment }}
      
      - name: Use env_status
        run: |
          echo "The environment status is: ${{ needs.deploy.outputs.env_status }}"
  
  # Deploy:
  #   needs: build
  #   strategy:
  #     matrix:
  #       include:
  #         - { environment: dev, runner-ap: windows-2019 }
  #         - { environment: qa, runner-ap: windows-2019 } 
          
  #   uses: ./.github/workflows/deployment2.yml
  #   with:
  #     target-ap: ${{ matrix.runner-ap }}
  #     target-env: ${{ matrix.environment }}



  # final:
  #   needs: Deploy
  #   runs-on: ubuntu-latest
  #   if: ${{ needs.approval.outputs.env_status == 'success' }}
  #   steps:
  #     - name: Final Step
  #       run: echo "Workflow passed!"


  # Deploy-ab:
  #   needs: build
  #   strategy:
  #     matrix:
  #       include:
  #         - { environment: dev, runner-ap: windows-2019, runner-dp: windows-latest }
  #         - { environment: qa, runner-ap: windows-2019, runner-dp: windows-latest } 
          
  #   uses: ./.github/workflows/deployment.yml
  #   with:
  #     target-ap: ${{ matrix.runner-ap }}
  #     target-dp: ${{ matrix.runner-dp }}
  #     target-env: ${{ matrix.environment }}
  # Deploy:
  #   needs: build
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       target: [windows-latest, ubuntu-latest]
  #       experimental: [true]
  #   uses: ./.github/workflows/deployment.yml
  #   with:
  #     target-exp: ${{ matrix.experimental }}
  #     target-env: ${{ matrix.target }}
  #   # secrets: inherit


# deploy-prod:
#     name: Deploy prod
#     needs: build
#     strategy:
#       matrix:
#         include:
#           - environment: windows-latest
#             # url: https://europe.my.service
#           - runner: windows-latest
#           - environment: ubuntu-latest
#             # url: https://europe.my.service
#           - runner: ubuntu-latest
#           # - env:
#           #     name: ${{vars.RUNNER}}
#     environment:
#       # url: ${{ matrix.url }}
#       name: ${{ matrix.environment }}
#     steps:
#     - name: deploy
#       uses: ./.github/workflows/deployment.yml
#       with:
#         # version: ${{ needs.deploy-staging.outputs.version }}
#         target-env: ${{ matrix.environment }}
#         target-runner: ${{ matrix.runner }}






  # Deploy-ab:
  #   needs: build
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       target: [windows-2019]
  #       # runner: [windows-2019]
  #   uses: ./.github/workflows/deployment2.yml
  #   with:
  #     target-env: ${{ matrix.target }}
  #     # target-runner: ${{ matrix.runner }}
  #   secrets: inherit
