name: Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Set Content of .env file
        run: |
          # read the content of .env file in PowerShell
          $envContent = Get-Content 'C:\actions-runner\.env'

          # loop through each line and set as GitHub ENV variable
          $envContent | ForEach-Object {
            $line = $_
            $parts = $line -split ':', 2
            $key = $parts[0].Trim()
            $value = $parts[1].Trim()
            echo "export $key=\"$value\"" >> $GITHUB_ENV
          }

      - name: Echo Content of .env file
        run: |
          # retrieve the GitHub ENV variables and echo the content
          echo "FORMS_DB_PUBLISHPROFILE=$FORMS_DB_PUBLISHPROFILE"
          echo "FORMS_DB_DACPAC=$FORMS_DB_DACPAC"
          echo "FORMS_DB_CONNECTIONSTRING=$FORMS_DB_CONNECTIONSTRING"
