name: Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Set Content of .env file
        run: |
          # read the content of .env file in PowerShell
          $envContent = Get-Content 'C:\actions-runner\.env'
          
          # loop through each line and echo the content
          foreach ($line in $envContent) {
            echo $line
          }

          # Assign each variable its respective value
          $FORMS_DB_PUBLISHPROFILE = $envContent | Select-String 'FORMS-DB_PUBLISHPROFILE' | ForEach-Object { ($_ -split ': ')[1] }
          $FORMS_DB_DACPAC = $envContent | Select-String 'FORMS-DB_DACPAC' | ForEach-Object { ($_ -split ': ')[1] }
          $FORMS_DB_CONNECTIONSTRING = $envContent | Select-String 'FORMS-DB_CONNECTIONSTRING' | ForEach-Object { ($_ -split ': ')[1] }

          # Echo each variable separately
          echo "FORMS-DB_PUBLISHPROFILE: $FORMS_DB_PUBLISHPROFILE"
          echo "FORMS-DB_DACPAC: $FORMS_DB_DACPAC"
          echo "FORMS-DB_CONNECTIONSTRING: $FORMS_DB_CONNECTIONSTRING"
