

name: build Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment' 
        required: true
        type: environment
 
jobs:
  runners-list:
    runs-on: ubuntu-latest
    environment: ubuntu-latest 
    outputs:
      matrix1: ${{ steps.demo.outputs.sample }}
    steps:
    - name: Run tests
      run: echo "${{ vars.ENV }}"
    - name: demo
      id: demo
      run: echo "sample=${{ vars.ENV }}" >> $GITHUB_OUTPUT

  Deploy-ab:
    needs: runners-list
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        target: ${{fromJSON(needs.build.outputs.matrix1)}}
    uses: ./.github/workflows/matrix2.yml
    with:
      target-env: ${{ matrix.target }}
    # secrets: inherit
