name: Configurable Build Matrix

on: push

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - id: set-matrix
        run: |
          branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')
          matrix=$(jq --arg branchName "$branchName" '. | map(select(.runOn == $branchName or .runOn == "always"))' matrix_includes.json)
          echo "matrix=${matrix}" >> $GITHUB_ENV
      - run: echo "${{ env.matrix }}"
  build-n-test:
    needs: matrix_prep
    runs-on: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    strategy:
      matrix:
        env: [ubuntu-latest]
        os: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    environment:
      name: ${{matrix.env}}
    steps:
      - run: echo "${{matrix.env}}"
      - name: "Deploy to Prod"
        run: |
          # Add your deployment script or commands for the chosen environment
          echo "Deploying to ${{matrix.env}}"
