name: Configurable Build Matrix

on: push

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      MATRIX: ''
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - id: set-matrix
        run: |
          branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')  
          matrix=$(jq --arg branchName "$branchName" 'map( 
              . | select((.runOn==$branchName) or (.runOn=="always"))
          )' matrix_includes.json)                
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_ENV
          echo "MATRIX=${matrix}" >> $GITHUB_ENV

  build-n-test:
    needs: matrix_prep
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    steps:
      - run: echo "${{fromJson(needs.matrix_prep.outputs.matrix)}}"
      - name: "Deploy to Prod"
        run: |
          # Add your deployment script or commands for the chosen environment
          echo "Deploying to ${{fromJson(needs.matrix_prep.outputs.matrix)}}"

