name: Configurable Build Matrix

on: push

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix=$(jq '.' matrix_includes.json)
          echo "$matrix"
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT

  build-n-test:
    needs: matrix_prep
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    environment: ubuntu-latest
    env:
      environment: ubuntu-latest
    steps:    
      - run: echo "${{env.environment}}"
      - name: "Deploy to ${{env.environment}}"
        run: |
          # Add your deployment script or commands for the chosen environment
          echo "Deploying to ${{env.environment}} "
      - name: Set matrix success flag
        id: set-matrix-success
        run: echo "matrix-success=true" >> $GITHUB_ENV

  matrix_prep1:
    runs-on: ubuntu-latest
    if: success()
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix=$(jq '.' matrix_includes1.json)
          echo "$matrix"
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT
      - name: Check if matrix_prep succeeded
        run: echo "Matrix preparation succeeded"

  build-n-test-windows:
    needs: matrix_prep1
    runs-on: windows-latest
    if: success()
    strategy:
      matrix: ${{fromJson(needs.matrix_prep1.outputs.matrix)}}
    environment: windows-latest
    env:
      environment: windows-latest
    steps:    
      - run: echo "${{env.environment}}"
      - name: "Deploy to ${{env.environment}}"
        run: |
          # Add your deployment script or commands for the chosen environment
          echo "Deploying to ${{env.environment}} "
