name:  NodeJS CI
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ubuntu-latest 
    outputs:
      matrix: ${{ steps.demo.outputs.sample }}
    steps:
    - name: Run tests
      run: echo "${{ vars.RUNNERS }}"
    - name: demo
      id: demo
      run: echo "sample=${{ vars.RUNNERS }}" >> $GITHUB_OUTPUT

  example_matrix:
    runs-on: ${{ matrix.version }}
    needs: build
    environment: demo
    strategy:
      matrix:
        version: ${{fromJSON(needs.build.outputs.matrix)}}
    steps:
    - name: devil
      run: echo "sample"
