name:  NodeJS CI
on:
  # push:
  #   branches:
  #     - "*"
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    outputs:
      matrix1: ${{ steps.demo.outputs.sample }}
      matrix2: ${{ steps.demo1.outputs.sample1 }}   
    steps:
    - name: Run tests
      run: echo "${{ vars.RUNNERS }}"
    - name: Run tests2
      run: echo "${{ vars.RUNNERS2 }}"
    - name: demo
      id: demo
      run: echo "sample=${{ vars.RUNNERS }}" >> $GITHUB_OUTPUT
    - name: demo1
      id: demo1
      run: echo "sample1=${{ vars.RUNNERS2 }}" >> $GITHUB_OUTPUT

  example_matrix:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.target-env }}
    # env:
    #   ${{ matrix.version }}_RUN: ${{vars.RUN}}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        version: ${{fromJSON(needs.build.outputs.matrix1)}}
    steps:
    - name: devil
      run: echo "${{ matrix.version }}"

  example_matrix1:
    runs-on: ${{ matrix.version }}
    needs: build
    environment: ${{ inputs.target-env }}
    # env:
    #   ${{ matrix.version }}_RUN2: ${{vars.RUN2}}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        version: ${{fromJSON(needs.build.outputs.matrix2)}}
    steps:
    - name: devil
      run: echo "${{ matrix.version }}"
